// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBrw5JzGoAyGcl1Go9dkvtuHAF0vtAoQg',
    appId: '1:797406662895:web:632cbdf38e50cfe8610b1a',
    messagingSenderId: '797406662895',
    projectId: 'finalcapture',
    authDomain: 'finalcapture.firebaseapp.com',
    storageBucket: 'finalcapture.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqI1FZiNzrWQ5GqKJk-abc123',
    appId: '1:797406662895:android:abc123',
    messagingSenderId: '797406662895',
    projectId: 'finalcapture',
    storageBucket: 'finalcapture.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0trlvF6pweK9X1fdFcRln4DFsGQnEOpc',
    appId: '1:797406662895:ios:d3105384ed279d00610b1a',
    messagingSenderId: '797406662895',
    projectId: 'finalcapture',
    storageBucket: 'finalcapture.firebasestorage.app',
    iosBundleId: 'com.kimchijjim.captureapp.kimchiJjim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqI1FZiNzrWQ5GqKJk-abc123',
    appId: '1:797406662895:macos:abc123',
    messagingSenderId: '797406662895',
    projectId: 'finalcapture',
    storageBucket: 'finalcapture.appspot.com',
    iosBundleId: 'com.kimchijjim.captureapp.kimchiJjim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqI1FZiNzrWQ5GqKJk-abc123',
    appId: '1:797406662895:windows:abc123',
    messagingSenderId: '797406662895',
    projectId: 'finalcapture',
    authDomain: 'finalcapture.firebaseapp.com',
    storageBucket: 'finalcapture.appspot.com',
    measurementId: 'G-ABC123',
  );
}
